### ISSUE TITLE
Support silent renew

### ISSUE THREAD

**Issue by MichaelBailly** [OpenPaaS-Suite/openpaas-auth-client#5]

**Comment by chamerling** [comment]
Silent renew is supported in oidc-client with a page each SPA must provide and used in an invisible iframe (plus some configuration).

**Comment by chamerling** [comment]
Linked PRs:

- https://github.com/OpenPaaS-Suite/esn-frontend-common-libs/pull/156
- https://github.com/OpenPaaS-Suite/openpaas-auth-client/pull/6
- https://github.com/OpenPaaS-Suite/esn-frontend-account/pull/80

Note that you will have to apply the same changes as for https://github.com/OpenPaaS-Suite/esn-frontend-account/pull/80 in all the SPAs to support silent renew.

This has been tested on keycloak, and there are no reason to not have this working on other OIDC providers just because this is only frontend code checking that the session is still OK using token stored on the browser.

To test it, I updated the access_token lifespan to 2 minutes (setting is to 1 minutes cause infinite loop on the client)

![Capture d’écran 2020-11-23 à 11 49 22](https://user-images.githubusercontent.com/264403/99953747-02266080-2d82-11eb-9714-456553549387.png)

Some browser logs:

![Capture d’écran 2020-11-23 à 11 58 32](https://user-images.githubusercontent.com/264403/99954588-4b2ae480-2d83-11eb-9195-d7537c55856e.png)

**Comment by tanandy** [comment]
Hi tks @chamerling can you confirm we can remove lemonldap RP iframe hack ? since we can use the RP iframe provided by oidc client or we need it also

https://ci.linagora.com/linagora/lgs/openpaas/openpaas-platform-docker-dev/commit/ddd460b830407d0f5f036f8c616ceb77e952986e

plz note that lemonldap is using opaque token and keycloak jwt token for access token fyi

**Comment by tanandy** [comment]
cc @tuanlc

**Comment by chamerling** [comment]
I am not aware of any Lemon hack, nor about how Lemon works. The oidc-client iframe should be enough. If not, Lemon probably has some OIDC implementation issues...
